# Generated by Django 3.2.16 on 2022-11-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('checkout', '0002_remove_orderitem_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
            preserve_default=False,
        ),
    ]
